name: Qodana Scan

on:
  workflow_call:
jobs:
  qodana-scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@a040a784cc28cb9cabdf884c4e8c32d0aa3fcdb3 # v2023.3.2
        with:
          args: "--fail-threshold,0"
      - uses: github/codeql-action/upload-sarif@4187e74d05793876e9989daffde9c3e66b4acd07 # v3
        if: always()
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json